# Generated by Django 3.1.6 on 2021-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20210301_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Holidays', 'Holidays'), ('Food', 'Food'), ('CAR', 'CAR'), ('Living', 'Living'), ('Hobbies', 'Hobbies'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Health', 'Health')], default='General', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
