# Generated by Django 3.1.6 on 2021-03-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20210302_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[(1, 'General'), (2, 'Holidays'), (3, 'Food'), (4, 'Car'), (5, 'Living'), (6, 'Hobbies'), (7, 'Shopping'), (8, 'Education'), (9, 'Health')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=1, max_length=10),
        ),
    ]
